# Generated by Django 4.1.7 on 2023-03-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='deleted_at',
            field=models.BooleanField(default=None),
        ),
    ]
