# Generated by Django 4.1.7 on 2023-03-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='deleted_at',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
